### PR TITLE
Allow installation of Monolog 2

### PR DESCRIPTION
**Pull request by tristanbes**
Allow installation of Monolog 2
I had to bump the version of PHP to `7.1` because of the `void` signature.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@tristanbes thanks for this contribution!! I couldn't fix the conflict merges myself, so I had to create a new PR in #29 ... but I kept your original commits, so you'll get full credit for your contribution. Thanks!

**Comment by Kocal** [comment]
Hi @javiereguiluz, it seems that Monolog 2 [requires PHP 7.2 or more](https://github.com/Seldaek/monolog/blob/master/composer.json#L16), so what about using the same requirement here?

Also, easy-log-handler allows Monolog 1 (which requires [PHP 5.3 or more](https://github.com/Seldaek/monolog/blob/1.x/composer.json#L16)) to be installed. But now since easy-log-handler requires PHP 7.1+, people won't be allowed to use Monolog 1, right?

What do you think?

We can have two version of `EasylogHandler`, one compatible with Monolog 2 and another one for Monolog 1. A similar thing was done on Symfony with PHPUnit 8 compatibility (see https://github.com/symfony/symfony/pull/32842 and [`ForwardCompatTestTrait`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Test/ForwardCompatTestTrait.php#L18)).
I'm seeing something like this:
```php
<?php

namespace EasyCorp\EasyLog;

use Monolog\Handler\StreamHandler;
use Monolog\Handler\Logger;

// Monolog 2 requires PHP 7.2+ and now use type hints for methods, like `void`.
if (Logger::API === 2) {
    class EasyLogHandler extends StreamHandler
    {
        /**
         * @param resource|string $stream
         */
        public function __construct($stream)
        {
            parent::__construct($stream);

            $this->formatter = new EasyLogFormatter();
        }

        /**
         * @param array $record
         */
        public function handle(array $record): bool
        {
            throw new \RuntimeException('The method "handle()" should never be called (call "handleBatch()" instead). This is probably caused by a wrong "monolog" configuration. Please read EasyLogHandler README instructions to learn how to configure and use it.');
        }

        /**
         * @param array $records
         */
        public function handleBatch(array $records): void
        {
            // if the log records were filtered (by channel, level, etc.) the array
            // no longer contains consecutive numeric keys. Make them consecutive again
            // before the log processing (this eases getting the next/previous record)
            $records = array_values($records);

            if ($records) {
                $this->write($this->getFormatter()->formatBatch($records));
            }
        }
    }
} else {
    class EasyLogHandler extends StreamHandler
    {
        /**
         * @param resource|string $stream
         */
        public function __construct($stream)
        {
            parent::__construct($stream);

            $this->formatter = new EasyLogFormatter();
        }

        /**
         * @param array $record
         */
        public function handle(array $record)
        {
            throw new \RuntimeException('The method "handle()" should never be called (call "handleBatch()" instead). This is probably caused by a wrong "monolog" configuration. Please read EasyLogHandler README instructions to learn how to configure and use it.');
        }

        /**
         * @param array $records
         */
        public function handleBatch(array $records)
        {
            // if the log records were filtered (by channel, level, etc.) the array
            // no longer contains consecutive numeric keys. Make them consecutive again
            // before the log processing (this eases getting the next/previous record)
            $records = array_values($records);

            if ($records) {
                $this->write($this->getFormatter()->formatBatch($records));
            }
        }
    }
}

```

**Comment by javiereguiluz** [comment]
@Kocal I think it's still going to work. Monolog 1 requires 5.3 or higher ... we require "higher", so we're complying with it. You can use Monolog 1 if you also use PHP 7.1 or higher.

Monolog 2 requires PHP 7.2 or higher ... if you use Monolog 2, you have PHP 7.2 ... so you comply too with our requirement: use PHP 7.1 or higher. You are using "higher".

**Comment by Kocal** [comment]
Yes but what if there are still people stuck at PHP 5.3?

PHP 5.3 is the minimum version Monolog 1 can works with, but easy-log-handler now requires to have PHP 7.1 or more.

**Comment by Kocal** [comment]
A new major version should have been tagged IMO.

Or revert PHP requirements to `>=5.3` and add the breaking layer compatibility posted before.

**Comment by javiereguiluz** [comment]
People stuck in PHP 5.3 will have to use the latest version before the PHP requirement bump. composer simply won't update this dependency anymore for them. 

About the major version, some people say it's not needed when bumping requirements and others say the opposite ... so it's not clear what to do. In any case, according to latest Packagist stats, almost nobody is using PHP 5.3 anymore and things have changed recently and people are upgrading more quickly (and PHP 7.4 is almost out 😱).

**Comment by Kocal** [comment]
Hum yes that's a good point.

I don't really know how it works in PHP/packagist world, but when a Node/npm package update its Node requirement, we try to _always_ release a new major version to prevent those kind of issues.

By the way Monolog 1 seems to be still maintened: https://github.com/Seldaek/monolog/commits/1.x

**Pull request closed without merging**
